### ISSUE TITLE
Remove Mapbox logo

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/ehrenamtskarte#355]
**Is your feature request related to a problem? Please describe.**
I am fairly sure that we do not need to show the Mapbox logo: https://stackoverflow.com/a/37554584

**Comment by maxammann** [comment]
Only attribution for https://openmaptiles.org/ is required. We already have this.

So lets remove it.

**Comment by klinzo** [comment]
Is there an easy way to disable this? I did not find anything in the docs. However, it is possible to just set the margins big enough so that it is not visible anymore (not really a nice solution though).

**Comment by Schedulaar** [comment]
The Flutter binding are not a nice solution per sé (they are shitty). So let's use a hack 👍🏽 
However, we could also solve it upstream in the maplibre bindings.

**Comment by maxammann** [comment]
Hm we actually could fix this upstream in maplibre and remove the logo, right? I mean there is no need for maplibre to display a mapbox logo, right?

**Comment by klinzo** [comment]
I am open to fixing it upstream, could you point me in the right direction? I am not quite familiar with mapbox/maplibre and how it plays together. If I want to fix it upstream, do I need the same margin hack (i.e. not taking `logoViewMargins` as an argument here but setting it manually to `Point(double.maxFinite, double.maxFinite)`) because maplibre uses mapbox under the hood? Or is there another way to do that?

**Comment by maxammann** [comment]
So Im still not 100% sure whether we are allowed to remove the logo. Maybe we can clarify this with the maplibre team.

**Comment by maxammann** [comment]
> When it comes to hiding the Mapbox logo, All non-Enterprise accounts are required to display the Mapbox logo when using any Mapbox maps. Therefore, you can't remove it.


But im not sure whether this is relevant for maplibre anymore. In fact it is not mapbox anymore.
